### ISSUE TITLE
geysers now make you drop items

### ISSUE THREAD

**Issue by puckhehexd** [SPACE-PIRATE-CREW/Space-Monkey-Mafia#1]
that's an issue

**Comment by FirewolfPrime** [comment]
You're a lil bitch

**Comment by Hahaplop** [comment]
hehexd

**Comment by puckhehexd** [comment]
hehexd

**Comment by puckhehexd** [comment]
puck is a wuss stop censoring me reeeeeeeeeeeeeeeeeeeee

**Comment by zero-potential** [comment]
-Bonnie 
dump your strategy stuff here

**Comment by zero-potential** [comment]
if you're in the mood for procrastination try today's google doodle
